//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Operater.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ListaNaloga", Namespace="http://schemas.datacontract.org/2004/07/Servis", ItemName="Korisnik")]
    [System.SerializableAttribute()]
    public class ListaNaloga : System.Collections.Generic.List<Operater.ServiceReference1.Korisnik> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Korisnik", Namespace="http://schemas.datacontract.org/2004/07/Servis")]
    [System.SerializableAttribute()]
    public partial class Korisnik : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Id_korisnikaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Korisnicko_imeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LozinkaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id_korisnika {
            get {
                return this.Id_korisnikaField;
            }
            set {
                if ((this.Id_korisnikaField.Equals(value) != true)) {
                    this.Id_korisnikaField = value;
                    this.RaisePropertyChanged("Id_korisnika");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Korisnicko_ime {
            get {
                return this.Korisnicko_imeField;
            }
            set {
                if ((object.ReferenceEquals(this.Korisnicko_imeField, value) != true)) {
                    this.Korisnicko_imeField = value;
                    this.RaisePropertyChanged("Korisnicko_ime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Lozinka {
            get {
                return this.LozinkaField;
            }
            set {
                if ((object.ReferenceEquals(this.LozinkaField, value) != true)) {
                    this.LozinkaField = value;
                    this.RaisePropertyChanged("Lozinka");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ListaKnjiga", Namespace="http://schemas.datacontract.org/2004/07/Servis", ItemName="Knjiga")]
    [System.SerializableAttribute()]
    public class ListaKnjiga : System.Collections.Generic.List<Operater.ServiceReference1.Knjiga> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Knjiga", Namespace="http://schemas.datacontract.org/2004/07/Servis")]
    [System.SerializableAttribute()]
    public partial class Knjiga : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AutorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double CenaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Id_knjigeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int KolicinaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NazivField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PopustField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Autor {
            get {
                return this.AutorField;
            }
            set {
                if ((object.ReferenceEquals(this.AutorField, value) != true)) {
                    this.AutorField = value;
                    this.RaisePropertyChanged("Autor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Cena {
            get {
                return this.CenaField;
            }
            set {
                if ((this.CenaField.Equals(value) != true)) {
                    this.CenaField = value;
                    this.RaisePropertyChanged("Cena");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id_knjige {
            get {
                return this.Id_knjigeField;
            }
            set {
                if ((this.Id_knjigeField.Equals(value) != true)) {
                    this.Id_knjigeField = value;
                    this.RaisePropertyChanged("Id_knjige");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Kolicina {
            get {
                return this.KolicinaField;
            }
            set {
                if ((this.KolicinaField.Equals(value) != true)) {
                    this.KolicinaField = value;
                    this.RaisePropertyChanged("Kolicina");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Naziv {
            get {
                return this.NazivField;
            }
            set {
                if ((object.ReferenceEquals(this.NazivField, value) != true)) {
                    this.NazivField = value;
                    this.RaisePropertyChanged("Naziv");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Popust {
            get {
                return this.PopustField;
            }
            set {
                if ((this.PopustField.Equals(value) != true)) {
                    this.PopustField = value;
                    this.RaisePropertyChanged("Popust");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ListaPorudzbina", Namespace="http://schemas.datacontract.org/2004/07/Servis", ItemName="Porudzbine")]
    [System.SerializableAttribute()]
    public class ListaPorudzbina : System.Collections.Generic.List<Operater.ServiceReference1.Porudzbine> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Porudzbine", Namespace="http://schemas.datacontract.org/2004/07/Servis")]
    [System.SerializableAttribute()]
    public partial class Porudzbine : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Id_knjigeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Id_korisnikaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Id_porudzbineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int KolicinaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id_knjige {
            get {
                return this.Id_knjigeField;
            }
            set {
                if ((this.Id_knjigeField.Equals(value) != true)) {
                    this.Id_knjigeField = value;
                    this.RaisePropertyChanged("Id_knjige");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id_korisnika {
            get {
                return this.Id_korisnikaField;
            }
            set {
                if ((this.Id_korisnikaField.Equals(value) != true)) {
                    this.Id_korisnikaField = value;
                    this.RaisePropertyChanged("Id_korisnika");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id_porudzbine {
            get {
                return this.Id_porudzbineField;
            }
            set {
                if ((this.Id_porudzbineField.Equals(value) != true)) {
                    this.Id_porudzbineField = value;
                    this.RaisePropertyChanged("Id_porudzbine");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Kolicina {
            get {
                return this.KolicinaField;
            }
            set {
                if ((this.KolicinaField.Equals(value) != true)) {
                    this.KolicinaField = value;
                    this.RaisePropertyChanged("Kolicina");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ILogIn")]
    public interface ILogIn {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogIn/LogIn", ReplyAction="http://tempuri.org/ILogIn/LogInResponse")]
        bool LogIn(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogIn/LogIn", ReplyAction="http://tempuri.org/ILogIn/LogInResponse")]
        System.Threading.Tasks.Task<bool> LogInAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogIn/VratiSveNaloge", ReplyAction="http://tempuri.org/ILogIn/VratiSveNalogeResponse")]
        Operater.ServiceReference1.ListaNaloga VratiSveNaloge();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogIn/VratiSveNaloge", ReplyAction="http://tempuri.org/ILogIn/VratiSveNalogeResponse")]
        System.Threading.Tasks.Task<Operater.ServiceReference1.ListaNaloga> VratiSveNalogeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogIn/RegistrujSe", ReplyAction="http://tempuri.org/ILogIn/RegistrujSeResponse")]
        string RegistrujSe(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogIn/RegistrujSe", ReplyAction="http://tempuri.org/ILogIn/RegistrujSeResponse")]
        System.Threading.Tasks.Task<string> RegistrujSeAsync(string username, string password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILogInChannel : Operater.ServiceReference1.ILogIn, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LogInClient : System.ServiceModel.ClientBase<Operater.ServiceReference1.ILogIn>, Operater.ServiceReference1.ILogIn {
        
        public LogInClient() {
        }
        
        public LogInClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LogInClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LogInClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LogInClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool LogIn(string username, string password) {
            return base.Channel.LogIn(username, password);
        }
        
        public System.Threading.Tasks.Task<bool> LogInAsync(string username, string password) {
            return base.Channel.LogInAsync(username, password);
        }
        
        public Operater.ServiceReference1.ListaNaloga VratiSveNaloge() {
            return base.Channel.VratiSveNaloge();
        }
        
        public System.Threading.Tasks.Task<Operater.ServiceReference1.ListaNaloga> VratiSveNalogeAsync() {
            return base.Channel.VratiSveNalogeAsync();
        }
        
        public string RegistrujSe(string username, string password) {
            return base.Channel.RegistrujSe(username, password);
        }
        
        public System.Threading.Tasks.Task<string> RegistrujSeAsync(string username, string password) {
            return base.Channel.RegistrujSeAsync(username, password);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IJavni")]
    public interface IJavni {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJavni/PrikazKnjiga", ReplyAction="http://tempuri.org/IJavni/PrikazKnjigaResponse")]
        Operater.ServiceReference1.ListaKnjiga PrikazKnjiga();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJavni/PrikazKnjiga", ReplyAction="http://tempuri.org/IJavni/PrikazKnjigaResponse")]
        System.Threading.Tasks.Task<Operater.ServiceReference1.ListaKnjiga> PrikazKnjigaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJavni/PoruciKnjigu", ReplyAction="http://tempuri.org/IJavni/PoruciKnjiguResponse")]
        void PoruciKnjigu(Operater.ServiceReference1.Knjiga kupljena, Operater.ServiceReference1.Korisnik ulogovanKorisnik);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJavni/PoruciKnjigu", ReplyAction="http://tempuri.org/IJavni/PoruciKnjiguResponse")]
        System.Threading.Tasks.Task PoruciKnjiguAsync(Operater.ServiceReference1.Knjiga kupljena, Operater.ServiceReference1.Korisnik ulogovanKorisnik);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IJavniChannel : Operater.ServiceReference1.IJavni, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class JavniClient : System.ServiceModel.ClientBase<Operater.ServiceReference1.IJavni>, Operater.ServiceReference1.IJavni {
        
        public JavniClient() {
        }
        
        public JavniClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public JavniClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JavniClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JavniClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Operater.ServiceReference1.ListaKnjiga PrikazKnjiga() {
            return base.Channel.PrikazKnjiga();
        }
        
        public System.Threading.Tasks.Task<Operater.ServiceReference1.ListaKnjiga> PrikazKnjigaAsync() {
            return base.Channel.PrikazKnjigaAsync();
        }
        
        public void PoruciKnjigu(Operater.ServiceReference1.Knjiga kupljena, Operater.ServiceReference1.Korisnik ulogovanKorisnik) {
            base.Channel.PoruciKnjigu(kupljena, ulogovanKorisnik);
        }
        
        public System.Threading.Tasks.Task PoruciKnjiguAsync(Operater.ServiceReference1.Knjiga kupljena, Operater.ServiceReference1.Korisnik ulogovanKorisnik) {
            return base.Channel.PoruciKnjiguAsync(kupljena, ulogovanKorisnik);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ISistem")]
    public interface ISistem {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistem/UnosKnjige", ReplyAction="http://tempuri.org/ISistem/UnosKnjigeResponse")]
        void UnosKnjige(int id, string naziv, string autor, double cena, int popust, int kolicina);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistem/UnosKnjige", ReplyAction="http://tempuri.org/ISistem/UnosKnjigeResponse")]
        System.Threading.Tasks.Task UnosKnjigeAsync(int id, string naziv, string autor, double cena, int popust, int kolicina);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistem/IzmenaKorisnika", ReplyAction="http://tempuri.org/ISistem/IzmenaKorisnikaResponse")]
        void IzmenaKorisnika(int id, string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistem/IzmenaKorisnika", ReplyAction="http://tempuri.org/ISistem/IzmenaKorisnikaResponse")]
        System.Threading.Tasks.Task IzmenaKorisnikaAsync(int id, string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistem/IzmenaKnjige", ReplyAction="http://tempuri.org/ISistem/IzmenaKnjigeResponse")]
        void IzmenaKnjige(Operater.ServiceReference1.Knjiga izmenjenaKnjiga);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistem/IzmenaKnjige", ReplyAction="http://tempuri.org/ISistem/IzmenaKnjigeResponse")]
        System.Threading.Tasks.Task IzmenaKnjigeAsync(Operater.ServiceReference1.Knjiga izmenjenaKnjiga);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistem/PregledPorudzbina", ReplyAction="http://tempuri.org/ISistem/PregledPorudzbinaResponse")]
        Operater.ServiceReference1.ListaPorudzbina PregledPorudzbina();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistem/PregledPorudzbina", ReplyAction="http://tempuri.org/ISistem/PregledPorudzbinaResponse")]
        System.Threading.Tasks.Task<Operater.ServiceReference1.ListaPorudzbina> PregledPorudzbinaAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISistemChannel : Operater.ServiceReference1.ISistem, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SistemClient : System.ServiceModel.ClientBase<Operater.ServiceReference1.ISistem>, Operater.ServiceReference1.ISistem {
        
        public SistemClient() {
        }
        
        public SistemClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SistemClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SistemClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SistemClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void UnosKnjige(int id, string naziv, string autor, double cena, int popust, int kolicina) {
            base.Channel.UnosKnjige(id, naziv, autor, cena, popust, kolicina);
        }
        
        public System.Threading.Tasks.Task UnosKnjigeAsync(int id, string naziv, string autor, double cena, int popust, int kolicina) {
            return base.Channel.UnosKnjigeAsync(id, naziv, autor, cena, popust, kolicina);
        }
        
        public void IzmenaKorisnika(int id, string username, string password) {
            base.Channel.IzmenaKorisnika(id, username, password);
        }
        
        public System.Threading.Tasks.Task IzmenaKorisnikaAsync(int id, string username, string password) {
            return base.Channel.IzmenaKorisnikaAsync(id, username, password);
        }
        
        public void IzmenaKnjige(Operater.ServiceReference1.Knjiga izmenjenaKnjiga) {
            base.Channel.IzmenaKnjige(izmenjenaKnjiga);
        }
        
        public System.Threading.Tasks.Task IzmenaKnjigeAsync(Operater.ServiceReference1.Knjiga izmenjenaKnjiga) {
            return base.Channel.IzmenaKnjigeAsync(izmenjenaKnjiga);
        }
        
        public Operater.ServiceReference1.ListaPorudzbina PregledPorudzbina() {
            return base.Channel.PregledPorudzbina();
        }
        
        public System.Threading.Tasks.Task<Operater.ServiceReference1.ListaPorudzbina> PregledPorudzbinaAsync() {
            return base.Channel.PregledPorudzbinaAsync();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IAdmin")]
    public interface IAdmin {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdmin/ObrisiKnjigu", ReplyAction="http://tempuri.org/IAdmin/ObrisiKnjiguResponse")]
        void ObrisiKnjigu(Operater.ServiceReference1.Knjiga knjiga);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdmin/ObrisiKnjigu", ReplyAction="http://tempuri.org/IAdmin/ObrisiKnjiguResponse")]
        System.Threading.Tasks.Task ObrisiKnjiguAsync(Operater.ServiceReference1.Knjiga knjiga);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdmin/ObrisiNalog", ReplyAction="http://tempuri.org/IAdmin/ObrisiNalogResponse")]
        void ObrisiNalog(Operater.ServiceReference1.Korisnik korisnik);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdmin/ObrisiNalog", ReplyAction="http://tempuri.org/IAdmin/ObrisiNalogResponse")]
        System.Threading.Tasks.Task ObrisiNalogAsync(Operater.ServiceReference1.Korisnik korisnik);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAdminChannel : Operater.ServiceReference1.IAdmin, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AdminClient : System.ServiceModel.ClientBase<Operater.ServiceReference1.IAdmin>, Operater.ServiceReference1.IAdmin {
        
        public AdminClient() {
        }
        
        public AdminClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AdminClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdminClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdminClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void ObrisiKnjigu(Operater.ServiceReference1.Knjiga knjiga) {
            base.Channel.ObrisiKnjigu(knjiga);
        }
        
        public System.Threading.Tasks.Task ObrisiKnjiguAsync(Operater.ServiceReference1.Knjiga knjiga) {
            return base.Channel.ObrisiKnjiguAsync(knjiga);
        }
        
        public void ObrisiNalog(Operater.ServiceReference1.Korisnik korisnik) {
            base.Channel.ObrisiNalog(korisnik);
        }
        
        public System.Threading.Tasks.Task ObrisiNalogAsync(Operater.ServiceReference1.Korisnik korisnik) {
            return base.Channel.ObrisiNalogAsync(korisnik);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IWeb")]
    public interface IWeb {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWeb/webLogIn", ReplyAction="http://tempuri.org/IWeb/webLogInResponse")]
        string webLogIn(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWeb/webLogIn", ReplyAction="http://tempuri.org/IWeb/webLogInResponse")]
        System.Threading.Tasks.Task<string> webLogInAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWeb/webRegistrujSe", ReplyAction="http://tempuri.org/IWeb/webRegistrujSeResponse")]
        string webRegistrujSe(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWeb/webRegistrujSe", ReplyAction="http://tempuri.org/IWeb/webRegistrujSeResponse")]
        System.Threading.Tasks.Task<string> webRegistrujSeAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWeb/webPrikazKnjiga", ReplyAction="http://tempuri.org/IWeb/webPrikazKnjigaResponse")]
        Operater.ServiceReference1.Knjiga[] webPrikazKnjiga();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWeb/webPrikazKnjiga", ReplyAction="http://tempuri.org/IWeb/webPrikazKnjigaResponse")]
        System.Threading.Tasks.Task<Operater.ServiceReference1.Knjiga[]> webPrikazKnjigaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWeb/webPoruciKnjigu", ReplyAction="http://tempuri.org/IWeb/webPoruciKnjiguResponse")]
        string webPoruciKnjigu(string idKnjige, string korisnickoIme, string kolicina);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWeb/webPoruciKnjigu", ReplyAction="http://tempuri.org/IWeb/webPoruciKnjiguResponse")]
        System.Threading.Tasks.Task<string> webPoruciKnjiguAsync(string idKnjige, string korisnickoIme, string kolicina);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWebChannel : Operater.ServiceReference1.IWeb, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebClient : System.ServiceModel.ClientBase<Operater.ServiceReference1.IWeb>, Operater.ServiceReference1.IWeb {
        
        public WebClient() {
        }
        
        public WebClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string webLogIn(string username, string password) {
            return base.Channel.webLogIn(username, password);
        }
        
        public System.Threading.Tasks.Task<string> webLogInAsync(string username, string password) {
            return base.Channel.webLogInAsync(username, password);
        }
        
        public string webRegistrujSe(string username, string password) {
            return base.Channel.webRegistrujSe(username, password);
        }
        
        public System.Threading.Tasks.Task<string> webRegistrujSeAsync(string username, string password) {
            return base.Channel.webRegistrujSeAsync(username, password);
        }
        
        public Operater.ServiceReference1.Knjiga[] webPrikazKnjiga() {
            return base.Channel.webPrikazKnjiga();
        }
        
        public System.Threading.Tasks.Task<Operater.ServiceReference1.Knjiga[]> webPrikazKnjigaAsync() {
            return base.Channel.webPrikazKnjigaAsync();
        }
        
        public string webPoruciKnjigu(string idKnjige, string korisnickoIme, string kolicina) {
            return base.Channel.webPoruciKnjigu(idKnjige, korisnickoIme, kolicina);
        }
        
        public System.Threading.Tasks.Task<string> webPoruciKnjiguAsync(string idKnjige, string korisnickoIme, string kolicina) {
            return base.Channel.webPoruciKnjiguAsync(idKnjige, korisnickoIme, kolicina);
        }
    }
}
